#!/usr/bin/env node
// Renders docs/reference/api-reference.md from the code repo's generated OpenAPI document.
//
// The spec is docs/openapi.json in kibertoad/cat-factory, itself generated from the contracts
// (contracts -> openapi.json -> the four SDK clients, with a CI guard there failing on drift). It
// has to stay there: it is the source every official client is generated from, and a copy here
// would be a second thing to keep in step. So this site RENDERS it rather than restating it, the
// same arrangement docs/reference/environment-variables.md has with the canonical variable list.
//
//   node scripts/sync-openapi.mjs                        # render; expects ../cat-factory
//   CAT_FACTORY_REPO=/path/to/cat-factory node scripts/sync-openapi.mjs
//   CAT_FACTORY_REF=some-branch node scripts/sync-openapi.mjs   # fetch over HTTPS instead
//   node scripts/sync-openapi.mjs --check                # fail if the rendered page is stale
//   node scripts/sync-openapi.mjs --verify               # offline checks on the committed page
//
// Run the render after pulling the code repo, and commit the result.
//
// The two check modes are split by what they depend on, exactly as sync-env-vars.mjs splits them:
//
//   --check   needs the spec, so it can only be as current as the OTHER repo. The two repos move
//             in paired pull requests, so this site legitimately leads or lags upstream main for
//             the life of a pair. As a blocking gate it would go red for a reason the pull request
//             under review cannot fix, so it runs on a schedule: red means "go re-sync".
//   --verify  depends only on files committed here, so it is deterministic and safe to block a
//             pull request on. It is what catches a hand-edited page and a dangling schema link.
//
// What this page deliberately does NOT try to be: the narrative. extend/public-api.md owns the
// integrator's first read (authenticating, picking a scope, the worked board workload, answering a
// parked run) and links here for the field level. A generated page cannot carry judgement, and a
// hand-written one cannot stay complete, so the two are split by exactly that line.
//
// That line is also why the two pages sit in DIFFERENT sections. "Drive Cat Factory from outside"
// is a job, so the narrative is in Extend; "what are this endpoint's fields" is a lookup, so the
// generated half is in Reference, beside the generated environment-variable list it is the twin of.
// The page therefore emits `../extend/…` links to its narrative, and carries a `redirectFrom` for
// the /extend/ URL it was first published at, which the code repo deep-links three times.

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const siteRoot = path.resolve(here, '..')
const docsRoot = path.join(siteRoot, 'docs')
const repoRoot = path.resolve(process.env.CAT_FACTORY_REPO ?? path.join(siteRoot, '..', 'cat-factory'))
const sourceRelPath = 'docs/openapi.json'
const sourcePath = path.join(repoRoot, ...sourceRelPath.split('/'))
const targetPath = path.join(docsRoot, 'reference', 'api-reference.md')
// Which revision to READ the spec from. Only this varies: the links the page EMITS always point at
// main, because they are published permalinks for readers, and letting the ref reach them would
// make --check fail on URL differences alone whenever it compared against a branch, which is
// precisely when it is being used to confirm a paired pull request.
const ref = process.env.CAT_FACTORY_REF ?? 'main'
const blob = 'https://github.com/kibertoad/cat-factory/blob/main'
const raw = `https://raw.githubusercontent.com/kibertoad/cat-factory/${ref}`
const sourceUrl = `${blob}/${sourceRelPath}`

const BANNER = '# GENERATED by scripts/sync-openapi.mjs. Do not edit by hand.'
const METHODS = ['get', 'post', 'put', 'patch', 'delete', 'head', 'options']

const failures = []

function fail(message) {
  failures.push(message)
}

// ---------------------------------------------------------------------------
// Heading slugs
// ---------------------------------------------------------------------------

// @mdit-vue/shared's rule, which is what VuePress renders this page's anchors with: map every RUN
// of whitespace or punctuation to one hyphen. Kept byte-identical in intent to check-repo-links.mjs
// rather than imported, because that script is a checker and this is an emitter: the shared thing
// is the RULE, and the rule is stated in both places with the same comment so a change to one is
// visible as a difference from the other.
const rControl = /[\u0000-\u001f]/g
const rSpecial = /[\s~`!@#$%^&*()\-_+=[\]{}|\\;:"'“”‘’<>,.?/]+/g
const rCombining = /[\u0300-\u036f]/g

function siteSlug(heading) {
  return heading
    .replace(/!\[([^\]]*)\]\([^)]*\)/g, '$1')
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
    .normalize('NFKD')
    .replace(rCombining, '')
    .replace(rControl, '')
    .replace(rSpecial, '-')
    .replace(/-{2,}/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/^(\d)/, '_$1')
    .toLowerCase()
}

// ---------------------------------------------------------------------------
// Markdown-safe text
// ---------------------------------------------------------------------------

// Spec prose is authored in the code repo and rendered here. It is trusted (it ships in the same
// repository as the code) but it is not written for a table cell: a newline ends a row and a pipe
// starts a new one, so both are neutralised wherever prose lands inside a table.
function cell(text) {
  return String(text ?? '')
    .replace(/\s*\n\s*/g, ' ')
    .replace(/\|/g, '\\|')
    .trim()
}

// Prose outside a table keeps its shape but must not open a heading or a list at column 0, which
// would break out of the operation it belongs to.
function prose(text) {
  return String(text ?? '')
    .split('\n')
    .map((line) => line.replace(/^(\s*)([#>]|[-*+]\s|\d+\.\s)/, '$1\\$2'))
    .join('\n')
    .trim()
}

// ---------------------------------------------------------------------------
// Schema rendering
// ---------------------------------------------------------------------------

const refName = (ref) => ref.replace('#/components/schemas/', '')
const schemaAnchor = (name) => `#${siteSlug(`\`${name}\``)}`
const schemaLink = (name) => `[\`${name}\`](${schemaAnchor(name)})`

// A schema's TYPE as one compact markdown phrase. Every branch is reachable from the spec as it
// stands; an unrecognised shape returns the literal `?` rather than an empty cell, so a spec that
// grows a keyword this does not model reads as a hole instead of as a field with no type.
function typeOf(schema) {
  if (!schema || typeof schema !== 'object') return '?'
  if (schema.$ref) return schemaLink(refName(schema.$ref))
  if (schema.const !== undefined) return `\`${JSON.stringify(schema.const)}\``
  if (schema.enum) return schema.enum.map((v) => `\`${JSON.stringify(v)}\``).join(' \\| ')
  if (schema.oneOf) return schema.oneOf.map(typeOf).join(' \\| ')
  if (schema.anyOf) return schema.anyOf.map(typeOf).join(' \\| ')
  if (schema.allOf) return schema.allOf.map(typeOf).join(' + ')
  if (schema.type === 'array') return `array of ${typeOf(schema.items)}`
  if (schema.type === 'object' || schema.properties) {
    if (schema.additionalProperties && typeof schema.additionalProperties === 'object') {
      return `map of ${typeOf(schema.additionalProperties)}`
    }
    return 'object'
  }
  if (schema.format) return `\`${schema.type}\` (${schema.format})`
  if (schema.type) return `\`${schema.type}\``
  return '?'
}

// The constraints an integration has to satisfy, which is the half of a field the name does not
// carry. Rendered as one phrase per field rather than a column each, because most fields have none.
function constraintsOf(schema) {
  if (!schema || typeof schema !== 'object') return ''
  const parts = []
  const { minLength, maxLength, minimum, maximum, pattern, format } = schema
  const chars = (n) => `${n} character${n === 1 ? '' : 's'}`
  if (minLength !== undefined && maxLength !== undefined) parts.push(`${minLength} to ${chars(maxLength)}`)
  else if (maxLength !== undefined) parts.push(`max ${chars(maxLength)}`)
  else if (minLength !== undefined) parts.push(`min ${chars(minLength)}`)
  if (minimum !== undefined && maximum !== undefined) parts.push(`${minimum} to ${maximum}`)
  else if (maximum !== undefined) parts.push(`max ${maximum}`)
  else if (minimum !== undefined) parts.push(`min ${minimum}`)
  if (pattern) parts.push(`pattern \`${pattern}\``)
  if (format && schema.type !== 'string') parts.push(`format \`${format}\``)
  return parts.join(', ')
}

// Flatten an object schema into table rows. An INLINE nested object becomes dotted rows rather than
// a second table: it has no name to link to, so a reader following `context.repo` has nowhere else
// to look it up. A $ref is never flattened, because it has its own section.
function fieldRows(schema, prefix = '', depth = 0) {
  const rows = []
  const required = new Set(schema.required ?? [])
  for (const [name, value] of Object.entries(schema.properties ?? {})) {
    const key = `${prefix}${name}`
    const inlineObject =
      depth < 3 && !value.$ref && value.properties && Object.keys(value.properties).length > 0
    rows.push({
      name: key,
      type: typeOf(value),
      required: required.has(name),
      notes: [constraintsOf(value), value.description ? cell(value.description) : '']
        .filter(Boolean)
        .join('. '),
    })
    if (inlineObject) rows.push(...fieldRows(value, `${key}.`, depth + 1))
  }
  return rows
}

function fieldTable(schema) {
  const rows = fieldRows(schema)
  if (!rows.length) return ''
  const lines = ['| Field | Type | Required | Notes |', '| --- | --- | --- | --- |']
  for (const row of rows) {
    lines.push(`| \`${row.name}\` | ${row.type} | ${row.required ? 'yes' : 'no'} | ${row.notes} |`)
  }
  return `${lines.join('\n')}\n`
}

// A schema section. Objects get a field table; everything else (a union, an array wrapper, a
// scalar) gets its type phrase, because a table with one nameless row says less than the phrase.
function renderSchema(name, schema) {
  const out = [`### \`${name}\``, '']
  if (schema.description) out.push(prose(schema.description), '')
  if (schema.oneOf || schema.anyOf) {
    const variants = schema.oneOf ?? schema.anyOf
    out.push(`One of ${variants.length} shapes.`, '')
    variants.forEach((variant, i) => {
      // A `const` property is the discriminator in every union the spec has today, so naming it
      // beats "Shape 3": it is what a reader switches on.
      const discriminator = Object.entries(variant.properties ?? {}).find(
        ([, value]) => value.const !== undefined,
      )
      const label = discriminator
        ? `\`${discriminator[0]}: ${JSON.stringify(discriminator[1].const)}\``
        : `Shape ${i + 1}`
      out.push(`**${label}**`, '')
      const table = fieldTable(variant)
      out.push(table || `${typeOf(variant)}\n`)
    })
    return `${out.join('\n')}\n`
  }
  const table = fieldTable(schema)
  out.push(table || `${typeOf(schema)}\n`)
  return `${out.join('\n')}\n`
}

// ---------------------------------------------------------------------------
// Operation rendering
// ---------------------------------------------------------------------------

function parameterTable(parameters, where) {
  const rows = (parameters ?? []).filter((p) => p.in === where)
  if (!rows.length) return ''
  const lines = [
    `**${where === 'path' ? 'Path' : where === 'query' ? 'Query' : 'Header'} parameters**`,
    '',
    '| Name | Type | Required | Notes |',
    '| --- | --- | --- | --- |',
  ]
  for (const p of rows) {
    const notes = [constraintsOf(p.schema), p.description ? cell(p.description) : '']
      .filter(Boolean)
      .join('. ')
    lines.push(`| \`${p.name}\` | ${typeOf(p.schema)} | ${p.required ? 'yes' : 'no'} | ${notes} |`)
  }
  return `${lines.join('\n')}\n`
}

// The body/response media types, as `type -> schema` pairs. A binary response has no schema worth
// linking, so it renders as its content type: that IS the contract for those endpoints.
function bodyTypes(content) {
  return Object.entries(content ?? {}).map(([mediaType, media]) => {
    const schema = media.schema
    if (schema?.$ref) return `${schemaLink(refName(schema.$ref))} (\`${mediaType}\`)`
    if (schema?.format === 'binary') return `binary (\`${mediaType}\`)`
    if (schema) return `${typeOf(schema)} (\`${mediaType}\`)`
    return `\`${mediaType}\``
  })
}

function renderOperation(method, urlPath, op) {
  const out = [`### ${op.summary}`, '']
  out.push(`\`${method.toUpperCase()} ${urlPath}\``)
  out.push('')
  const scope = op['x-min-scope']
  if (scope) out.push(`Minimum scope: \`${scope}\`.`, '')
  else {
    // Every operation in the spec carries one today. If one stops, the page must say so rather than
    // render a scope-less endpoint that reads as unauthenticated.
    fail(`${method.toUpperCase()} ${urlPath} has no x-min-scope; the reference cannot state its scope`)
    out.push('Minimum scope: not declared in the spec.', '')
  }
  if (op.deprecated) out.push('::: warning Deprecated', 'This operation is scheduled for removal.', ':::', '')
  if (op.description) out.push(prose(op.description), '')

  const pathParams = parameterTable(op.parameters, 'path')
  const queryParams = parameterTable(op.parameters, 'query')
  if (pathParams) out.push(pathParams)
  if (queryParams) out.push(queryParams)

  if (op.requestBody) {
    const types = bodyTypes(op.requestBody.content)
    out.push(
      `**Request body** (${op.requestBody.required ? 'required' : 'optional'}): ${types.join(', ')}`,
      '',
    )
  }

  const responses = Object.entries(op.responses ?? {})
  if (responses.length) {
    const lines = ['**Responses**', '', '| Status | Body | Meaning |', '| --- | --- | --- |']
    for (const [status, response] of responses) {
      const types = bodyTypes(response.content)
      lines.push(`| \`${status}\` | ${types.join(', ') || 'empty' } | ${cell(response.description)} |`)
    }
    out.push(`${lines.join('\n')}\n`)
  }
  return `${out.join('\n')}\n`
}

// ---------------------------------------------------------------------------
// The page
// ---------------------------------------------------------------------------

function collectOperations(spec) {
  const operations = []
  for (const [urlPath, item] of Object.entries(spec.paths ?? {})) {
    for (const method of METHODS) {
      const op = item[method]
      if (!op) continue
      const tags = op.tags ?? []
      if (tags.length !== 1) {
        // The grouping IS the navigation. An untagged operation would fall off the page and a
        // multi-tagged one would appear twice, and both read as a complete reference.
        fail(
          `${method.toUpperCase()} ${urlPath} has ${tags.length} tags; this page groups by exactly one`,
        )
      }
      operations.push({ method, urlPath, op, tag: tags[0] ?? 'Other' })
    }
  }
  return operations
}

function render(specText) {
  const spec = JSON.parse(specText)
  const operations = collectOperations(spec)

  // Summaries become the operation anchors, so a collision would silently point two endpoints at
  // one heading. Caught here rather than left to a reader following the wrong link.
  const bySlug = new Map()
  for (const { method, urlPath, op } of operations) {
    const slug = siteSlug(op.summary ?? '')
    if (!op.summary) fail(`${method.toUpperCase()} ${urlPath} has no summary to title its section`)
    if (bySlug.has(slug)) {
      fail(
        `two operations share the heading "${op.summary}" (${bySlug.get(slug)} and ` +
          `${method.toUpperCase()} ${urlPath}); one of them needs a distinct summary upstream`,
      )
    }
    bySlug.set(slug, `${method.toUpperCase()} ${urlPath}`)
  }

  // Tag order comes from the spec's own `tags` array, so the page's section order is upstream's
  // decision rather than this script's. A tag used by an operation but absent there still renders,
  // at the end, rather than dropping its operations.
  const declared = (spec.tags ?? []).map((t) => t.name)
  const used = [...new Set(operations.map((o) => o.tag))]
  const tagOrder = [...declared.filter((t) => used.includes(t)), ...used.filter((t) => !declared.includes(t))]
  const tagDescriptions = new Map((spec.tags ?? []).map((t) => [t.name, t.description]))

  const scopes = spec['x-public-api-scopes'] ?? []
  const bearer = spec.components?.securitySchemes?.bearerAuth

  const out = []
  out.push('---')
  out.push(BANNER)
  out.push('editLink: false')
  // The page's own outline would otherwise be ~120 entries, one per operation and schema, which is
  // a sidebar nobody can read. The two in-page indexes below do that job instead, so the sidebar
  // stays at the three sections and the anchors are still there for anyone linking one.
  out.push('sidebarDepth: 1')
  // The URL this page was first published at. Emitted here rather than hand-added, because the
  // frontmatter is regenerated on every sync and a hand-added key would vanish on the next one.
  out.push('redirectFrom:')
  out.push('  - /extend/api-reference.html')
  out.push('---')
  out.push('')
  out.push('# API Endpoint Reference')
  out.push('')
  out.push(
    `Every operation the public API (\`/api/v1\`) serves, with its scope, parameters and payload ` +
      `shapes. Generated from the [OpenAPI document in the code repository](${sourceUrl}), which is ` +
      `itself generated from the contracts the server routes are built from, so this page cannot ` +
      `drift from the running surface.`,
  )
  out.push('')
  out.push(
    `Surface version **${spec.info?.version ?? 'unknown'}**. ${operations.length} operations across ` +
      `${tagOrder.length} groups.`,
  )
  out.push('')
  out.push('::: tip Start on the guide, not here')
  out.push(
    'This page is the field level. [Public API](../extend/public-api.md) is the page to read first: ' +
      'how to mint a key, which scope to pick, the worked board workload, how to answer a run that ' +
      'parks, and how the error envelope and paging work. Reach for an ' +
      '[official SDK](../extend/sdks.md) before hand-rolling HTTP, or point a generator at the spec ' +
      'linked above.',
  )
  out.push(':::')
  out.push('')
  out.push('## Authenticating')
  out.push('')
  if (bearer?.description) out.push(prose(bearer.description), '')
  out.push(
    'Every call carries the key as a bearer token and is scoped to that key\'s workspace. Each key ' +
      'holds one scope on an inclusive ladder, so a higher scope grants everything below it:',
  )
  out.push('')
  out.push(`\`${scopes.join('` → `')}\``)
  out.push('')
  out.push(
    'Each operation below states the LOWEST scope that admits it. A key below that line is refused ' +
      'with `403 insufficient_scope`; an absent or unknown key is refused with `401`.',
  )
  out.push('')
  out.push('## Operations')
  out.push('')
  out.push(tagOrder.map((tag) => `[${tag}](#${siteSlug(tag)})`).join(' · '))
  out.push('')

  for (const tag of tagOrder) {
    out.push(`### ${tag}`)
    out.push('')
    const description = tagDescriptions.get(tag)
    if (description) out.push(prose(description), '')
    const inTag = operations.filter((o) => o.tag === tag)
    for (const { method, urlPath, op } of inTag) {
      // Operations are H4 under their tag's H3: one level per nesting step, so the outline is
      // well-formed even though the frontmatter keeps it out of the sidebar.
      out.push(renderOperation(method, urlPath, op).replace(/^### /, '#### '))
    }
  }

  out.push('## Schemas')
  out.push('')
  out.push(
    'The payload shapes the operations above reference. Field names, types and constraints are the ' +
      'contract; the narrative for what each one means lives on the page that owns the feature.',
  )
  out.push('')
  const schemas = spec.components?.schemas ?? {}
  const schemaNames = Object.keys(schemas).sort()
  out.push(schemaNames.map((name) => schemaLink(name)).join(' · '))
  out.push('')
  for (const name of schemaNames) {
    out.push(renderSchema(name, schemas[name]))
  }

  out.push('---')
  out.push('')
  out.push(
    'Next: [Public API](../extend/public-api.md) for the narrative and the worked examples, or ' +
      '[SDKs](../extend/sdks.md) for a generated client that already speaks all of this.',
  )
  out.push('')

  const page = out.join('\n').replace(/\n{3,}/g, '\n\n')

  // Two headings that slug the same silently merge: the second anchor never resolves and every link
  // to it lands on the first. The operation-summary check above cannot see this one, because a
  // collision here can be between a schema and a tag, or a tag and an operation.
  const seen = new Map()
  for (const heading of headingsOf(page)) {
    const slug = siteSlug(heading)
    if (seen.has(slug)) fail(`two headings slug to #${slug}: "${seen.get(slug)}" and "${heading}"`)
    else seen.set(slug, heading)
  }

  return page
}

// ---------------------------------------------------------------------------
// Offline verification of whatever is committed at docs/reference/api-reference.md
// ---------------------------------------------------------------------------

function headingsOf(markdown, depth = 6) {
  const heading = new RegExp(`^#{1,${depth}}\\s+(.*?)\\s*$`)
  const found = []
  let inFence = false
  const lines = markdown.split('\n')
  let i = 0
  if (lines[0] === '---') {
    i = 1
    while (i < lines.length && lines[i] !== '---') i++
    i++
  }
  for (; i < lines.length; i++) {
    if (/^\s*(```|~~~)/.test(lines[i])) {
      inFence = !inFence
      continue
    }
    if (inFence) continue
    const m = heading.exec(lines[i])
    if (m) found.push(m[1])
  }
  return found
}

function verify(generated) {
  // 1. Still a generated page. A hand edit that strips the banner is the failure this design exists
  //    to prevent, and it is invisible until the next sync silently overwrites the edit.
  if (!generated.includes(BANNER)) {
    fail('docs/reference/api-reference.md has lost its GENERATED banner')
  }
  const h1s = headingsOf(generated, 1)
  if (h1s.length !== 1) {
    fail(`expected exactly one H1, found ${h1s.length}: ${h1s.join(' | ')}`)
  }

  // 2. Every schema link resolves to a schema section ON THIS PAGE. This is the check worth having:
  //    the links are emitted from $refs and the sections from the schema map, so a schema referenced
  //    but not exported would render as a link to nowhere, and nothing else here would notice.
  const anchors = new Set(headingsOf(generated).map(siteSlug))
  const dangling = new Set()
  for (const m of generated.matchAll(/\]\(#([a-z0-9_-]+)\)/g)) {
    if (!anchors.has(m[1])) dangling.add(m[1])
  }
  if (dangling.size) {
    fail(
      `${dangling.size} in-page link(s) point at a heading this page does not have: ` +
        `${[...dangling].join(', ')}`,
    )
  }

  // 3. Every cross-page link resolves to a real page and heading.
  for (const m of generated.matchAll(/\]\((\.[^)\s#]+\.md)(#[^)\s]*)?\)/g)) {
    const [, target, anchor = ''] = m
    const filePath = path.resolve(path.dirname(targetPath), target)
    if (!existsSync(filePath)) {
      fail(`links to ${target}, which does not exist on this site`)
      continue
    }
    if (anchor) {
      const theirs = new Set(headingsOf(readFileSync(filePath, 'utf8')).map(siteSlug))
      if (!theirs.has(anchor.slice(1))) fail(`links to ${target}${anchor}, but that page has no such heading`)
    }
  }

  // 4. Every operation section states a scope. A reference that silently omits one reads as an
  //    endpoint with no authorization requirement, which is the worst thing this page could say.
  const operationHeadings = headingsOf(generated, 4).length
  const scopeLines = (generated.match(/^Minimum scope: /gm) ?? []).length
  return { anchors: anchors.size, operationHeadings, scopeLines }
}

// ---------------------------------------------------------------------------

async function readSource() {
  if (existsSync(sourcePath)) return readFileSync(sourcePath, 'utf8')
  // No local checkout: fetch the spec over HTTPS so the scheduled drift check can run without
  // cloning a second repository.
  const url = `${raw}/${sourceRelPath}`
  const response = await fetch(url)
  if (!response.ok) {
    console.error(
      `Could not read ${sourcePath}, and fetching ${url} returned ${response.status}.\n` +
        'Clone kibertoad/cat-factory beside this repo, or set CAT_FACTORY_REPO to its path.',
    )
    process.exit(1)
  }
  return response.text()
}

function report() {
  if (failures.length) {
    for (const failure of failures) console.error(`error: ${failure}`)
    process.exit(1)
  }
}

const mode = process.argv.includes('--check')
  ? 'check'
  : process.argv.includes('--verify')
    ? 'verify'
    : 'render'

if (mode === 'verify') {
  const stats = verify(readFileSync(targetPath, 'utf8'))
  if (stats.scopeLines === 0) fail('no operation on the page states a minimum scope')
  report()
  console.log(
    `api-reference.md verified: generated banner intact, ${stats.anchors} anchors, ` +
      `every in-page link resolves, ${stats.scopeLines} operations state a scope`,
  )
} else {
  const rendered = render(await readSource())
  report()
  if (mode === 'check') {
    const current = readFileSync(targetPath, 'utf8')
    if (current !== rendered) {
      console.error(
        `docs/reference/api-reference.md is stale against kibertoad/cat-factory@${ref}.\n` +
          'Run: node scripts/sync-openapi.mjs',
      )
      process.exit(1)
    }
    console.log(`api-reference.md is up to date with kibertoad/cat-factory@${ref}`)
  } else {
    writeFileSync(targetPath, rendered)
    console.log(`wrote ${path.relative(siteRoot, targetPath)} from ${sourceUrl}`)
  }
}
